/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package players;

import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import mapps.MAPPSView;
import mapps.Presentator;
import org.jdesktop.swingx.util.OS;
import usersettings.SettingsLoader;

/**
 * objekt na zobrazovanie textových súborov
 * @author Ľubomír Petrus
 */
public class TxtViewer extends javax.swing.JFrame {
    
    /**
     * premenná indikujúca, či bol už zobrazený aspoň jeden dokument
     */
    public static boolean WasTextViewed = false;
    
    /**
     * premenná indikujúca momentálne zobrazenie textového súboru
     */
    public static boolean isTViewed = false;
    
    /**
     * časovač dĺžky zobrazenia textového súboru
     */
    public static Timer timer;
    
    /**
     * hlavné okno zobrazovača
     */
    public JFrame frame = this;

    /**
     * konštruktor objektu TxtViewer
     */
    public TxtViewer() {
        initComponents();

        frame.setLocation(20,100);

        if(OS.isWindows()){
            Font fnt = new Font("Arial", 0, 12);
            jEditorPane1.setFont(fnt);
        }else{
            Font fnt = new Font("DejaVu Sans", 0, 12);
            jEditorPane1.setFont(fnt);
        }

        GraphicsEnvironment e = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Font[] fonts = e.getAllFonts();
        
        ArrayList <String> stringFonts = new ArrayList <String>();
        for(int i = 0; i < fonts.length; i++){
            stringFonts.add(fonts[i].getName());
        }
        
        ComboBoxModel model = new DefaultComboBoxModel(stringFonts.toArray());
        jComboBox2.setModel(model);
        
        jComboBox2.setSelectedItem(jEditorPane1.getFont().getName());
        jComboBox1.setSelectedItem(String.valueOf(jEditorPane1.getFont().getSize()));
        
        frame.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                Presentator.secondMultimediaSearchTimer.restart();
                timer.cancel();
                MAPPSView.isPaused = false;
                isTViewed = false;
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        setTitle("Txt Viewer");
        setAlwaysOnTop(true);

        jLabel1.setText("Font size : ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6", "7", "8", "9", "10", "12", "14", "16", "18", "20", "22", "24", "26", "28", "30" }));
        jComboBox1.setSelectedIndex(4);
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jEditorPane1.setEditable(false);
        jScrollPane1.setViewportView(jEditorPane1);

        jLabel2.setText("Font: ");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, 0, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeInvisible
        changeFont();
    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeInvisible

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        changeFont();
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    /**
     * metóda na zmenu písma
     */
    public void changeFont() {
        Font f = new Font(jComboBox2.getSelectedItem().toString(), 0, Integer.parseInt(jComboBox1.getSelectedItem().toString()));
        jEditorPane1.setFont(f);
    }
    
    /**
     * začiatok zobrazenia textového súboru
     * @param file - cesta k súboru na zobrazenie
     */
    public void loadTextFile(String file){

            isTViewed = true;
            
            FileInputStream FIS = null;
            try {
                FIS = new FileInputStream(file);
                DataInputStream DIS = new DataInputStream(FIS);
                BufferedReader reader = new BufferedReader(new InputStreamReader(DIS));
                
                StringBuilder str = new StringBuilder();
                String tempStr = reader.readLine();
                while(tempStr != null){
                    str.append(tempStr);
                    str.append(System.getProperty("line.separator"));
                    tempStr = reader.readLine();
                }
                
                jEditorPane1.setText(str.toString());
                this.setVisible(true);
                WasTextViewed = true;
                
                timer = new Timer();
                int time = (int) (SettingsLoader.getInstance().getDocumentsShowingLength() * 1000);
                timer.schedule(new RemindTask(this), time);
                
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(frame, "ERROR: Cannot load file. Please parse gps file again. ", "ERROR", JOptionPane.ERROR_MESSAGE);
            } finally {
                try {
                    if(FIS != null){
                        FIS.close();
                    }
                } catch (IOException ex) {

                }
            }                  
    }
    
    
    /**
     * skrytie okna zobrazovača
     */
    public void setVisibleFalse() {
      this.setVisible(false);
  }

    /**
    * opätovné spustenie časovača dĺžky zobrazenia textového súboru
    */
    public void restartTimer() {
      timer = new Timer();
      int time = (int) (SettingsLoader.getInstance().getDocumentsShowingLength() * 1000);
      timer.schedule(new RemindTask(this), time);
  }

 static class RemindTask extends TimerTask {
     
     private JFrame frame;
     
     public RemindTask(JFrame frame){
         super();
         this.frame = frame;
     }

        public void run() {

            timer.cancel();

            if (Presentator.isClosingWindows == true) {
                    PictureViewer.frame.setVisible(false);
                    frame.setVisible(false);
                }

            isTViewed = false;

            Presentator.secondMultimediaSearchTimer.restart();

            if (Presentator.isClosingWindows == true) {
                    PictureViewer.frame.setVisible(false);
                }

        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    public static javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
